name: Release

env:
  IMAGE_NAME: activemq-artemis-operator
  
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: sudo apt-get install pass

      - name: Checkout the repo
        uses: actions/checkout@v2
      
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1

      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      
      - name: Prepare
        id: prep
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/v}
          PLATFORMS=linux/amd64,linux/ppc64le
          IMAGE_NAME=activemq-artemis-operator


      - name: Login to quay.io
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: "Build and push"
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./build/Dockerfile
          platforms: env.PLATFORMS
          tags:  ${{ secrets.QUAY_NAMESPACE }}/${{ steps.prep.outputs.IMAGE_NAME }}:${{ steps.prep.outputs.IMAGE_TAG }},${{ secrets.QUAY_NAMESPACE }}/${{ steps.prep.outputs.IMAGE_NAME }}:latest
          push: true
